### ISSUE TITLE
Add a --version flag

### ISSUE THREAD

**Issue by tseemann** [broadinstitute/pilon#1]
Makes it a lot easier to audit components of pipelines in a systematic manner.
```
% java -jar pilon-1.13.jar --version
pilon 1.13
```

**Comment by w1bw** [comment]
Good idea. I'll take care of this in the next release.

**Comment by w1bw** [comment]
I committed the change. It will be included in 1.14 when that gets released...if I don't think I'll add more functionality soon, I'll just release this. Example:

% pilon --version
Pilon version 1.13-1-g6f3c547 Sun Oct 4 19:38:34 2015 -0400
%

**Comment by tseemann** [comment]
Cheers!
