### ISSUE TITLE
How to run pilon

### ISSUE THREAD

**Issue by leggylas** [broadinstitute/pilon#138]
Hi, I am new to bioinformatics and I am having a hard time to understand the tutorial dataset, I use a Mac air m1, 8gb RAM, 
I have finished the assembly process of my fastq with canu, this is the result: 
[DRR131199_1.contigs.fasta.gz](https://github.com/broadinstitute/pilon/files/7240143/DRR131199_1.contigs.fasta.gz)

However, I want to polish the result using reads from illumina which is this one: 
https://www.ebi.ac.uk/ena/browser/view/DRX123936?show=reads

What code should I input to the terminal in order for me to run pilon? 
Any help is much appreciated 🙏

**Comment by Vasudha-pai** [comment]
hiii i need help with this, could you please guide me with the codes?

**Comment by Ayat-code12** [comment]
Hi, I need help with this too, please share the codes. TIA
