### ISSUE TITLE
--threads argument no longer supported

### ISSUE THREAD

**Issue by cpavloud** [broadinstitute/pilon#147]
Hello! 

I am trying to run pilon (v 1.24) on an HPC cluster using slurm. My command (in my sh script) is

`java -Xmx200G -jar pilon-1.24.jar --iupac --genome purged.fa --frags SRR_uniq_sorted.bam --diploid --threads 40 --outdir pilon_flye
`

But I get the error

`Pilon version 1.24 Thu Jan 28 13:00:45 2021 -0500
--threads argument no longer supported; ignoring!` 

Is there another flag for the threads in version 1.24?

**Comment by ethering** [comment]
A belated answer, but the release notes for 1.24 state:

> Support for the experimental --threads option has been removed. It was implemented by an ugly hack which no longer works in modern scala, and it was a resource hog in any case. I hope to revisit multithreading again in the future.

https://github.com/broadinstitute/pilon/releases/tag/v1.24
