### ISSUE TITLE
Adding _pilon to FASTA header lines causes a mismatch with the associated .vcf file

### ISSUE THREAD

**Issue by danwiththeplan** [broadinstitute/pilon#20]
Hi, I noticed that when running Pilon the output FASTA has `_pilon` appended to the name, and any text after a whitespace in the FASTA header line is removed.
However the associated `.vcf` file retains the original FASTA header line. The result is that the `.vcf` file does not match the FASTA header line, which causes problems when loading into a genome browser.

**Comment by w1bw** [comment]
The VCF has the original headers because the variants are called (and the bams aligned) relative to the input genome. How do you want to display the output genome in the browser? I suppose you could do an alignment of the output genome back to the original.
