### ISSUE TITLE
Feature request: option to correct indels but not SNPs

### ISSUE THREAD

**Issue by danwiththeplan** [broadinstitute/pilon#21]
Hi, is it possible to include an option to fix indels but not SNPs?
Currently there is this option:

`--fix bases`: try to fix individual bases and small indels

but this fixes both indels and snps.

**Comment by w1bw** [comment]
I meant to put that in "the next release", but I totally forgot.  I'll try to get it in soon!

**Comment by danwiththeplan** [comment]
Thanks so much for the fast response! The PI I am working with is of the opinion that indels are different from SNPS in that indels are more likely to be a result of PacBio not dealing with homopolymers well, whereas SNPS may be genuine. So good to have an option here. Much appreciated.

**Comment by w1bw** [comment]
I have implemented this in the code. There are one or two other fixes I want to look at, but I plan to release this sometime in the next week. Again, sorry I forgot about it last time!
