### ISSUE TITLE
Request for small-scale test data for workshops

### ISSUE THREAD

**Issue by danwiththeplan** [broadinstitute/pilon#23]
Hi, I run a lot of genome assembly workshops, have one coming up soon, and I would really like to include a Pilon run on some test data that is small and fast to run. We tend to run the workshop as a virtualbox VM, so size and runtime have to be kept to a minimum. Is there any such data available?

**Comment by w1bw** [comment]
That's a good idea, but I don't know of a small dataset currently available, and I'm not sure if.when I'll have time to generate one. I'll keep it in mind, though!
