### ISSUE TITLE
negative genome size

### ISSUE THREAD

**Issue by bwlang** [broadinstitute/pilon#24]
I see this when I start up pilon

<pre>
Genome: ../quiver_polished_0307.fasta
Fixing bases, gaps, local
Input genome size: -1800804444
</pre>

Looks like genomeSize is a long...  and my genome is only 2.5Gbase
I thought about maybe some individual contig lengths are overflowing, but
my longest is 32961348, which should not overflow an int. 

Any ideas?

**Comment by w1bw** [comment]
Oops. It's probably using a signed 32 bit int for the total size. I'll see if I can put in a quick fix, as I'm about to do a new release.
