### ISSUE TITLE
number of threads

### ISSUE THREAD

**Issue by JahnDavik** [broadinstitute/pilon#25]
Hi,
I am running pilon on a canu assembly with ~4k contigs with an average length of ~100kb. In the manual/tutorial I have it is stated that the '--threads' command line option is experimental. Is there any reason not to use more threads than the default (=1)?

jahn

**Comment by w1bw** [comment]
You should get some speedup, but not orders of magnitude, as the multithreading is pretty coarse-grained (it processes the input fasta elements in parallel, at the expense of memory and more garbage collecting). In my tests on a smaller genome, I got 3-4x using --threads 8.
