### ISSUE TITLE
Pilon OutOfMemoryError

### ISSUE THREAD

**Issue by lijingjing1** [broadinstitute/pilon#26]
Hi 

I use pilon to correct a genome size about 2.7 Gb on Memory 1T CPU 96 machine with args -Xmx512G.

At last it make a error about "Caused by: java.lang.OutOfMemoryError: Java heap space".So what is the problem of my question?

**Comment by w1bw** [comment]
With a genome that large, you will almost certainly want to subset the input genome either by breaking it into pieces, or by using the --targets argument to process subsets of the fasta elements. You also might want to subset the BAMs, but if you do, please try to include not only the reads which align to the scaffolds in question, but also their mates.

Several people on the pilon-users mailing list have some up with best practices for handling large genomes...you might want to ask there (I don't have much personal experience with it; I only offer advice!).

**Comment by nick-youngblut** [comment]
I'm running `pilon` in a snakemake pipeline where it's not so straight-forward to subsample reads only too many reads are in the input. I'm assuming that `pilon` has hard-coded the amount of memory used for Java. Can the java memory be added as a option for `pilon`? Knowing how much  memory is used by Java would also be useful for SGE jobs.

**Comment by CristianRiccio** [comment]
I installed `pilon` with `conda` here: `/Users/user/anaconda/bin/pilon`. I opened that file in vim and changed the memory limit from 1G to 14G and now it's running whereas before it stopped immediately and complained about insufficient memory.

**Comment by Tipplynne** [comment]
@CristianRiccio where did you change the mem limit option?

**Comment by CristianRiccio** [comment]
@Tipplynne Try installing it with conda and change the memory in the file `Users/user/anaconda/bin/pilon` like I did.

**Comment by KasperThystrup** [comment]
One approach when using Pilon in a pipeline (e.g. snakemake) is to add the java flag to the pilon command.
`pilon --genome x --threads y ...  -Xmx3G`
