### ISSUE TITLE
pilon runtime

### ISSUE THREAD

**Issue by madhubioinfo** [broadinstitute/pilon#37]
Hello is there is any way to reduce the runtime of pilon? Iam running 60Mb genome and its the third day of run still its not been done, i checked the log file its still doing 48% read of genome assembly , thanks

**Comment by w1bw** [comment]
Sorry it has taken me so long to respond, but I'm finally catching up on pilon support issues.

It's hard to say without knowing more about your data and genome. For larger genomes, if you care mostly about fixing base errors and small indels, then "--fix bases" will be faster and use a smaller memory footprint. If you want the full set of improvements, such as gap filling, correcting local misassemblies where re-assembly is required, you will probably either need to use more memory or break the processing into subsets using "--target".
