### ISSUE TITLE
Very old version of htsjdk.jar

### ISSUE THREAD

**Issue by tseemann** [broadinstitute/pilon#42]
I just noticed pilon uses a quite old version of `htsjdk.jar` (1.x).

Would it be worth upgrading to the latest 2.x series?
I worry that *many* bugs have been fixed in the last two years?

http://samtools.github.io/htsjdk/

**Comment by w1bw** [comment]
Pilon doesn't do very sophisticated things with htsjdk; mostly scanning reads in a bam and querying reads mapping to a given contig, so I haven't worried about keeping very up-to-date. However, since I'm working on some experimental additions to pilon, I'll keep that in mind!
