### ISSUE TITLE
Generating FastQ of assembly from Pilon output

### ISSUE THREAD

**Issue by dbrowneup** [broadinstitute/pilon#43]
Hello, I am wondering if anyone has tried to generate a FastQ file of their assembly from the Pilon output? I'm also running Arrow to polish my assembly with PacBio data and it spits out a FastQ file with quality scores for each base in the assembly. I'm very interested in comparing the mean quality scores for each scaffold as polished by Pilon or Arrow.

**Comment by w1bw** [comment]
Pilon does not generate a fastq for output base quality, but I suppose one could generate one by post-processing the output FASTA and VCF files. To do it right, we would have to get an idea of "real" accuracy vs implied accuracy from qual scores....if errors were truly random, then it wouldn't be so hard, but that's not always the case!
