### ISSUE TITLE
Can pilon work with an assembly with ambiguous bases?

### ISSUE THREAD

**Issue by caonetto** [broadinstitute/pilon#49]
Hi,
I merged multiple nanopore contigs using illumina data but I have some ambiguous bases in the final contig. I want to polish this final contig with the original illumina data. Will pilon work with this ambiguous bases?

Thanks!

**Comment by w1bw** [comment]
I believe Pilon will "correct" those bases to a non-ambiguous code, assuming it has enough good coverage. If that doesn't seem to be happening, I'll look into it further!
