### ISSUE TITLE
Option to put output in --outdir XXXX

### ISSUE THREAD

**Issue by tseemann** [broadinstitute/pilon#6]
Would be nice if `pilon` hand an `--outdir` option to make a folder and put everything in it.

This is particularly true for the `--tracks` option which writes a lot of stuff.

**Comment by w1bw** [comment]
That's a good suggestion; I will consider it for a future release. Pilon is mostly in maintenance-mode at this point, but I will always try to fix bugs and incorporate suggestions like this on a time-available basis!

**Comment by w1bw** [comment]
I just included this in Pilon version 1.17 (just released). Thanks again for the suggestion.

**Comment by tseemann** [comment]
Thanks for doing this @w1bw.

Can you suggest any replacements to Pilon for correcting assemblies with Illumina data?
