### ISSUE TITLE
GATK Indel Realigner

### ISSUE THREAD

**Issue by ArashBayat** [broadinstitute/pilon#62]
Hi,
I know that GATK HaplotypeCaller does not require Indel Realignment as it locally re-assemble the genome. However, Pilon does not seem to have such re-assembling step.

Does the Pilon have indel realignment itself?

Could running GATK indel realigner prior to Pilon enhance the polishing quality of Pilon?

Thanks

**Comment by orangeSi** [comment]
pilon maybe has local assembly：
 --fix fixlist
          A comma-separated list of categories of issues to try to fix:
            "snps": try to fix individual base errors;
            "indels": try to fix small indels;
            "gaps": try to fill gaps;
            "local": try to detect and fix local misassemblies;
            "all": all of the above (default);
