### ISSUE TITLE
Chimeric sequences

### ISSUE THREAD

**Issue by faraz89** [broadinstitute/pilon#68]
Hi,
Will pilon polishing remove chimeric sequences also in case if they are present in the input data?

Thanks.

**Comment by BurlEarl** [comment]
if you are talking about breaking mis-jointed scaffolds, Pilon will not do that.  REAPR will do this, but I haven't tested it yet..  http://www.sanger.ac.uk/science/tools/reapr

**Comment by w1bw** [comment]
That's correct. I hope to add that capability in the future.
