### ISSUE TITLE
too many contigs

### ISSUE THREAD

**Issue by woodoo46** [broadinstitute/pilon#7]
I have quite a few contigs that I want to correct. Is it OK if I split the contig file --genome option into several files, each of whihch contains only a small number of contigs?

**Comment by w1bw** [comment]
Yes, people working with a large number of fasta elements (scaffolds, contigs) in their input genome often take this approach.  Another way is to use the --targets command line option, which can either specify a list of input elements to process right on the command line, or specify a file which contains a list of fasta elements to process.

Good luck!
