### ISSUE TITLE
pilon for rna-seq

### ISSUE THREAD

**Issue by manuelsmendoza** [broadinstitute/pilon#85]
Hi!

I have a question related to #50...  I wanna to build a transcriptome of reference (without genome) and to do so I've thought: (1) *de novo* assembly by [Trinity](https://github.com/trinityrnaseq/trinityrnaseq), (2) clustering the transcripts to reduce redundancy using [grouper](https://github.com/COMBINE-lab/grouper) and then (3) make a consensus reference for each cluster using pilon.

Which is your opinion?   

cheers,
~MM.

**Comment by OnlyHigh** [comment]
Hi @manuelsmendoza,
As a opinion: 
Right now I'm polishing mtDNA from RNA-seq reads, the problem with this is that numts interfere with the polishing process so..., if you're transcripts are single copy and don't present that many SNPs you could/should try it, but if you have many variants (for whatever reason) be careful...

**Comment by manuelsmendoza** [comment]
Thanks so much @OnlyHigh!
The second scenario is my case... I'm working with hypervariable organisms with many mutations along the genome... Finally, I've written a little script to extract the "consensus" sequence from Grouper.
